[versions]
okhttp = "4.10.0"
kotlin = "1.7.20"
agp = "7.2.0"

[libraries]
jwt = "com.auth0:java-jwt:4.0.0"
gson = "com.google.code.gson:gson:2.9.1"
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
dokkaKotlinAsJavaPlugin = { module = "org.jetbrains.dokka:kotlin-as-java-plugin", version.ref = "kotlin" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
pluginPublish = "com.gradle.plugin-publish:1.0.0"